### ISSUE TITLE
Order Creation - Inputs.

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#104]
# Problem number one:
**I've put in this:**
![image](https://user-images.githubusercontent.com/11192971/57585479-0a44e500-74e9-11e9-8871-999f847054fc.png)
**But the SQL Database took in this:**
![image](https://user-images.githubusercontent.com/11192971/57585482-14ff7a00-74e9-11e9-920e-3d6b66644971.png)
**The problem is somewhere in the JS that populates the dropdowns most likely.**
_notice length and width are also too low._

**Comment by MalteMagnussen** [comment]
See #59 maybe.

**Comment by HrBjarup** [comment]
See [Pull request 105](https://github.com/HrBjarup/Fog-Carport/pull/105)
