### ISSUE TITLE
Tilted Roof JS Issue

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#106]
# Problem:
**When you order carport with tilted roof:**
![image](https://user-images.githubusercontent.com/11192971/57585503-47a97280-74e9-11e9-9c6a-11208e1e9031.png)
**The bug points to here:**
![image](https://user-images.githubusercontent.com/11192971/57585505-54c66180-74e9-11e9-89ab-c26576899615.png)

**Comment by Runi-VN** [comment]
This will be fixed with work done on task#194
