### ISSUE TITLE
AlgorithmException should (probably) be deleted

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#107]
algorithmException currently only handles roof_tile_id in flatroofcalc

roof_tile_id is already handled in frontend and backend (order) -- so no reason for this one, single use of a custom exception.

**Comment by MalteMagnussen** [comment]
[Related Task](https://tree.taiga.io/project/maltemagnussen-fog/task/143?kanban-status=1592820)

**Comment by Castau** [comment]
Is being fixed in thes task [https://tree.taiga.io/project/maltemagnussen-fog/task/143?kanban-status=1592821](url)
