### ISSUE TITLE
After #90 - Update how the shed menu is populated

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#108]
Change the population of the shed wall- and shed floor-menu using JS. (Should only be worked on when issue #90 is finsihed)

**Comment by HrBjarup** [comment]
Currently working on an enhancement but there are issues with EL and I can't find the source of the problem

**Comment by Runi-VN** [comment]
moved to sprint 5 to close sprint 4.

**Comment by Runi-VN** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/160
