### ISSUE TITLE
Empty constructors in commands

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#110]
Several commands have empty pointless constructors that should be deleted

**Comment by MalteMagnussen** [comment]
Yeah, I wasn't sure if they're needed or not, because they were autogenerated, so I just let them be. Please go ahead and delete them if they're useless.

**Comment by Castau** [comment]
This issues has been fixed along with [Task#188](https://tree.taiga.io/project/maltemagnussen-fog/task/188?kanban-status=1592822)
[Pull equest](https://github.com/HrBjarup/Fog-Carport/pull/128)
