### ISSUE TITLE
Customers cannot create new orders

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#116]
The order-table in DB needs a FK to an employee-id to work. This id is unavailable when logged in as a customer. The DDL-script should most likely be updated and probably also the OrderMapper.

**Comment by MalteMagnussen** [comment]
Should probably simply delete the employee table since we don't intend to use it any longer.

**Comment by MalteMagnussen** [comment]
I assume this should be fixed after all our Mockito work is done on that branch.

**Comment by MalteMagnussen** [comment]
Test works , but I get a "Message: Roof tiles has to be an integer." when I try to order a carport in the browser.
