### ISSUE TITLE
View SVG can be optimized

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#125]
There are still bugs in the viewSVG.jsp-page. There are several points that need to be optimized.

**Comment by MalteMagnussen** [comment]
Arrow Heads are missing.
![image](https://user-images.githubusercontent.com/11192971/57980619-00157000-7a2e-11e9-8004-17f02cfdcce2.png)

**Comment by HrBjarup** [comment]
Fixed in [pull request #144](https://github.com/HrBjarup/Fog-Carport/pull/144)
