### ISSUE TITLE
OrderCarport is broken

### ISSUE THREAD

**Issue by Castau** [HrBjarup/Fog-Carport#129]
When ordering a carport with raised roof you get this message and is logged out:
![image](https://user-images.githubusercontent.com/35559774/57969289-c2eda700-7975-11e9-9882-45bb84c803ca.png)

When you order a carport with flat roof you get this message:
![image](https://user-images.githubusercontent.com/35559774/57969296-dc8eee80-7975-11e9-8ff9-9b7084523a5b.png)

The first problem probably stems from this:
![image](https://user-images.githubusercontent.com/35559774/57969307-00523480-7976-11e9-8a4a-3438d9acc668.png)

as it returns the map-object and not an integer:
![image](https://user-images.githubusercontent.com/35559774/57969318-2546a780-7976-11e9-9002-ca3f1ba069f6.png)

**Comment by MalteMagnussen** [comment]
Technically you're not logged out, only sent to the log in site.

**Comment by Castau** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/130
