### ISSUE TITLE
If you press "Tilbage til den valgte ordre" on partslist page, it doesn't fill in the order.

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#136]
![image](https://user-images.githubusercontent.com/11192971/57980527-11aa4800-7a2d-11e9-9f88-e32fbfa93d96.png)

**Comment by HrBjarup** [comment]
Fixed in [pull request #143](https://github.com/HrBjarup/Fog-Carport/pull/143)
