### ISSUE TITLE
If you choose incline for roof, choose tiles, then choose no incline, it looks like this

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#137]
![image](https://user-images.githubusercontent.com/11192971/57980545-33a3ca80-7a2d-11e9-9e00-860f6085ed52.png)

**Comment by Runi-VN** [comment]
Already fixed on a branch that have yet to be merged as it is still a WIP*:
https://github.com/HrBjarup/Fog-Carport/commit/9245c72734f20c017f5dd8e1d84a24a1ff407d54

*(Still WIP due to the task/user story being deprioritized)
