### ISSUE TITLE
Frontpage form (createCarport form) is visible/standard when logged in

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#148]
The form on the front page contains the name-, phone-, email- and password-input fields when you are logged in. This should be changed - the front page should either look like the other orderCarport-page or it should be unavailable or just redirect to the orderCarport-page when the session contains a user.

**Comment by MalteMagnussen** [comment]
Can probably be fixed with c:if test="${not empty customer}" then show the form.

Otherwise show something else. c:if test="${empty customer}"

But yeah, otherwise just make it unavailable and redirect to orderCarport. (In validation maybe in FrontController)

**Comment by MalteMagnussen** [comment]
#173
