### ISSUE TITLE
Måske skal tegningerne vises fra starten når viewSVG loades

### ISSUE THREAD

**Issue by Castau** [HrBjarup/Fog-Carport#158]
Forslaget går på at den samlede tegning vises når siden loades og at de to toggle-knapper synligt er togglet TIL (og kan så slåes fra og til igen efter behag).

**Comment by HrBjarup** [comment]
Skal det være noget a la [det her](https://getbootstrap.com/docs/4.3/components/buttons/#toggle-states) ?

**Comment by HrBjarup** [comment]
Fixed in PR [164](https://github.com/HrBjarup/Fog-Carport/pull/164)
