### ISSUE TITLE
Material with 0 quantity is added to the partslist

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#165]
So far I have only seen this happen when an order has an incline of 0 degrees.

**Comment by HrBjarup** [comment]
![image](https://user-images.githubusercontent.com/44898491/58237849-622fe700-7d46-11e9-8b55-5c28d84fa392.png)

**Comment by Runi-VN** [comment]
Please see https://github.com/HrBjarup/Fog-Carport/pull/185
