### ISSUE TITLE
"Tagtype" dropdown not populated on frontpage (not logged in)

### ISSUE THREAD

**Issue by Castau** [HrBjarup/Fog-Carport#168]
The dropdown "Tagtype" is not populated with options on the frontpage i.e when not logged in. 

![image](https://user-images.githubusercontent.com/35559774/58269439-db036300-7d87-11e9-8b28-99ab28862662.png)

**Comment by MalteMagnussen** [comment]
Fix here #173

**Comment by Castau** [comment]
> Fix here #173

The issue is not fixed on branch ChangeOrderCarport:
![image](https://user-images.githubusercontent.com/35559774/58330316-ea8db500-7e36-11e9-9cd8-b7a5a8f818b2.png)

**Comment by MalteMagnussen** [comment]
@Castau Now it is.

**Comment by Castau** [comment]
> @Castau Now it is.

It's not fixed :) the error is still there when you're logged in and have completed an order and wants to make one more or when you've tried to submit an incomplete order.

**Comment by HrBjarup** [comment]
I think it is fixed now? At least it works on [this branch](https://github.com/HrBjarup/Fog-Carport/pull/176)

**Comment by HrBjarup** [comment]
Nvm, it doesn't work

**Comment by MalteMagnussen** [comment]
I think it works now on #173
