### ISSUE TITLE
"Helptext not available" should be "Ingen hjælpetekst" or something similar.

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#170]

**Comment by Runi-VN** [comment]
could probably set a default value in DB and filter on that

**Comment by MalteMagnussen** [comment]
Filter? What do you mean? :) 
The helptext is simply taken from the DB and placed on the instance of MaterialModel.
![image](https://user-images.githubusercontent.com/11192971/58351904-5b9a9000-7e6a-11e9-8bc2-f0205d2a72b0.png)
So to change the helptext we only need to change it in the "Default" part of the create script I think.

**Comment by MalteMagnussen** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/175/commits/3c97750871465d8a463554a4f2454ab814bd737a

**Comment by MalteMagnussen** [comment]
Just need to run the script again on the server and it should be fine.
