### ISSUE TITLE
Can one of the favicons be deleted?

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#179]
Not sure if both are used anyways
![image](https://user-images.githubusercontent.com/37186286/58370404-6dca0c00-7f06-11e9-8117-c0586e2c4765.png)

**Comment by Castau** [comment]
Yes - I just put the two versions in, in case you liked one better than the other. I'll delete favicon2

**Comment by Castau** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/188
