### ISSUE TITLE
DBConnection: "Too Many Connections" etc

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#180]
During my algorithm refactoring today I managed to experience the bug that we are all familiar with - `Too many connections`. And that was with only me using the server.

I thought I'd create an issue so that we can track conversations and solution proposals.

Here is an overview of **one of the issues** we are getting:
[Too many Connections](https://paste.ee/p/A5r6u)

Up till now we have tried:  
* Using our own version of the DBConnector
* Using a teacher supplied DBConnector
* Using [Apache DBCP](https://commons.apache.org/proper/commons-dbcp/)
* Using [HikariCP](https://github.com/brettwooldridge/HikariCP) (currently)

Further attempts to fix it:
Pull https://github.com/HrBjarup/Fog-Carport/pull/175
Pull https://github.com/HrBjarup/Fog-Carport/pull/196

**Comment by Runi-VN** [comment]
Malte has a suggested solution here:
https://github.com/HrBjarup/Fog-Carport/pull/175

**Comment by Runi-VN** [comment]
An email was sent to AKA last night in hope for a solution before deadline wednesday 29/05

**Comment by MalteMagnussen** [comment]
Yes. Sent an email. Will follow up if we get an answer.

**Comment by Runi-VN** [comment]
Props to AKA for answering on a saturday ❤️

**Comment by MalteMagnussen** [comment]
> **Too many connections**
> Malte has a suggested solution here:
> #175

This is now merged on dev. Let's hope this alleviates some of the suspected leaks.

**Comment by MalteMagnussen** [comment]
![image](https://user-images.githubusercontent.com/11192971/58384089-0c756c00-7fde-11e9-8524-13dddbc65c84.png)
![image](https://user-images.githubusercontent.com/11192971/58384092-15663d80-7fde-11e9-987e-85355a20a7ad.png)
Problemet er nok at I ikke tager højde for flere tråde i koden til DatabaseConnetor’s open og close metoder. Det sikreste er nok at bruge DataSource’en direkte i jeres mappere, specielt da I bruger Hikaru som allerede implementerer en connection pool, og så er det “threadsafe”:
![image](https://user-images.githubusercontent.com/11192971/58384099-2911a400-7fde-11e9-80b5-01bcbef67629.png)

**Comment by MalteMagnussen** [comment]
New fix: #196
