### ISSUE TITLE
Consider adding ZEROFILL to database

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#181]
> When you select a column with type ZEROFILL it pads the displayed value of the field with zeros up to the display width specified in the column definition. Values longer than the display width are not truncated. Note that usage of ZEROFILL also implies UNSIGNED.

```SQL
CREATE TABLE yourtable (x INT(8) ZEROFILL NOT NULL, y INT(8) NOT NULL);
INSERT INTO yourtable (x,y) VALUES
(1, 1),
(12, 12),
(123, 123),
(123456789, 123456789);
SELECT x, y FROM yourtable;
```   
>Result:
```
        x          y
 00000001          1
 00000012         12
 00000123        123
123456789  123456789
```

[Source](https://stackoverflow.com/questions/5256469/what-is-the-benefit-of-zerofill-in-mysql)

---
For our purpose we could add it to `id_order` as int(6) or something like it.
`id_order` would then display as:
000001
000002
000003
000004
000005

**Comment by MalteMagnussen** [comment]
What would the benefit be? I don't understand, sorry.

**Comment by Runi-VN** [comment]
> What would the benefit be? I don't understand, sorry. Could you elaborate?

The only benefit is visual.

I believe it is industry standard (...) to not display IDs as `1` but with leading zeros such as `0001`.


Lets see if I can show it visually...For us it could be of "help" in terms of alligning the partslist table, as all IDs have the same size (6 digits):

```
Varenr | Antal | Enhed | (...)
-----------------------------
000029 | 6     | Stk   |
000290 | 6     | Stk   |
```
vs
```
Varenr | Antal | Enhed | (...)
-----------------------------
1   | 6     | Stk   |
29  | 6     | Stk   |
290 | 6     | Stk   |
2900| 6     | Stk   |
```
(Obviously Bootstrap helps with this, **but numbers are still gonna look wonky going from 1 to 2 to three digits)

**Comment by Runi-VN** [comment]
Another argument, lmao, look how difficult it was to format that `shit`

![image](https://user-images.githubusercontent.com/37186286/58375050-a12e8a00-7f4a-11e9-9d3d-a55da63ae097.png)

**Comment by MalteMagnussen** [comment]
Ah okay. I see. Great explanation. Also it shouldn't be too hard to implement this tbh.

**Comment by Runi-VN** [comment]
> Ah okay. I see. Great explanation. Also it shouldn't be too hard to implement this tbh.

I think it is as simple as this:

**Change the following**
```SQL
  `id_order` INT NOT NULL AUTO_INCREMENT,
```
To:
```SQL
  `id_order` INT(6) ZEROFILL NOT NULL AUTO_INCREMENT,
```
Where **INT(6)** can be whatever we want it to be.

**Comment by Runi-VN** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/197
