### ISSUE TITLE
Consider adding "Unit" to partslist display

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#182]
Since we have a `Unit` field (And Fog does too) I think we should display it.
![image](https://user-images.githubusercontent.com/37186286/58372685-90b5e980-7f21-11e9-8b26-fc7b2d2ae172.png)

At the same time I propose we show ID first, and ONLY show ID to Employee.

**To sum the suggestion(s) up:**

Employee View:
```
Varenr | Antal | Enhed | (...)
-----------------------------
000029 | 6     | Stk   |
```

Customer view:
```
Antal | Enhed | (...)
-----------------------------
6     | Stk   |
```

**Comment by MalteMagnussen** [comment]
I'll look into this tomorrow.

**Comment by Runi-VN** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/189
