### ISSUE TITLE
Order Status is displayed in English on viewOrder.jsp

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#183]
Easiest fix for now is to just translate it..
if status == Finalized  
write "Færdig"

![image](https://user-images.githubusercontent.com/37186286/58372830-d1aefd80-7f23-11e9-8038-d04c42affa89.png)

**Comment by Castau** [comment]
yes - the problem in changing it in the DB now, is that it's used many places, especially in the jsp and I'm unsure if we'll find all the places. Should i just make a quickfix here alone?

**Comment by Castau** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/190
