### ISSUE TITLE
Consider putting Jacoco coverage online

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#204]
Jacoco generates an `index.html` file just like Javadoc; it can be put online in the same way as Javadoc currently is. [needs another directory]

**Comment by Runi-VN** [comment]
Attempt here: https://github.com/HrBjarup/Fog-Carport/commit/52207e35ab154e1d5239cf9a9485c0c67a4d660f

**Comment by MalteMagnussen** [comment]
Its live at: https://hrbjarup.github.io/Fog-Carport/jacoco/
