### ISSUE TITLE
Optimize footer.jsp and header.jsp imports

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#33]
footer.jsp and header.jsp currently have imports that are unnecessary on various other .jsp-pages. Those imports (such as js-imports)  should be moved to the .jsp-pages that actually use them. (E.g. js-validation for user input is not needed on the front page)

**Comment by MalteMagnussen** [comment]
Pretty sure this is now covered by https://github.com/HrBjarup/Fog-Carport/issues/44

Let's close this one?

**Comment by Runi-VN** [comment]
added details from this issue to #44. closing.
