### ISSUE TITLE
Post technical meeting issues

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#44]
[Changes during meeting](https://github.com/HrBjarup/Fog-Carport/pull/43).  
Document [here](https://docs.google.com/document/d/1K8rEY3u1VQB22vUCymMYeEemu_yjpIZHvWGTGId7Ies/edit#).

**CSS/Javascript**
- ~~Preferably only one file for each.~~
  - ~~Javascript is cached and should not be causing troubles loading on all pages.~~
  - ~~CSS is fine in one global file.~~
    - ~~If necessary, there are workarounds for loading specific stylesheets independently.~~

Fixed here: Pull https://github.com/HrBjarup/Fog-Carport/pull/77

~~**We should consider the discussed idea of reversing header & footer functions for .JSP pages.**
Issue: ```footer.jsp and header.jsp currently have imports that are unnecessary on various other .jsp-pages.```~~
We made these changes and had them approved by AKA: https://github.com/HrBjarup/Fog-Carport/pull/67

**Singleton issues**
See document

**Mapper issues (category)**
Fixed on bugfix branch: https://github.com/HrBjarup/Fog-Carport/commit/1b7c3d32cdceaaca48fd3300f65ed6976d9b14ff 
~~After removing singletons and what not we should be good to go.  
There are multiple solutions: Changing values, SQL Inner Joins, multiple methods, transactions...  
@MalteMagnussen & @Runi-VN discussed the idea of changing `MaterialModel`'s field `category` to an int, as it is in the database, and just use that. Then in the .JSP Bill of Materials we would differentiate between numbers 1 (wood), 2 (misc.) & 3 (roof).~~

**Other issues**:
- Screws - What, how?
  - Suggested: add a lot of packs. for the future: count (depends on PO accepting user story)  

@MalteMagnussen has this method to calculate screws:  
```JAVA
/**
    private void addScrews(PartslistModel bom, MaterialModel screws, int packamount, int screwamount){
        int restskruer = screwamount % packamount;
        int amountofpacks = screwamount / packamount;
        if (restskruer > 0)
        {
            amountofpacks++;
        }
        screws.setQuantity(amountofpacks);
        bom.addMaterial(screws);
    }
```
~~Helptext~~
Malte added a solution here: https://github.com/HrBjarup/Fog-Carport/pull/118

  -~~Suggested: Add two new tables, **helptext** and **helptext_category**.
    - helptext: 
       * helptext_id INT (PK)
       * helptext VARCHAR
       * material_id INT
       * helptext_category_id INT (FK)
    - helptext_category
       * helptext_category_id INT (PK)
       * helptext_category_name VARCHAR~~

~~Where `helptext_category_name` would then be the name of the package of the items, for example: `carport` or `carport-shed`~~

* Database:
  * `Order.status` needs to have a ruleset for statusses, as we are using VARCHAR and not ENUM.
    * Ideally we should change `Orders.status` to an ENUM.  

If not:
Lets keep `Orders.status` as a varchar, but lets define the possible states:
* Processing (Order received, waiting on seller)
* Awaiting (Bill sent, awaiting customer)
*((Payment received))*
* Verified (Continue to send rest of order)
* Finished (Order finished)  

(This is just a draft, please assist in possible names, states, etc)

**Comment by MalteMagnussen** [comment]
Will make a Bug Fixes branch for all of these things.

**Comment by MalteMagnussen** [comment]
**Fix for the following pushed to branch "BugFixes"**
> Mapper issues

We had an issue with the MaterialMapper, namely the getMaterial(int id) method. Should be fixed with commit 1b7c3d.

**Comment by MalteMagnussen** [comment]
[Tests for DataMappers.](https://datsoftlyngby.github.io/dat2sem2019Spring/Modul5/Week3-TEST/IntegrationstestDatabase.html)

**Comment by MalteMagnussen** [comment]
Make sure we have [Code Coverage.](https://datsoftlyngby.github.io/dat2sem2019Spring/Modul5/Week3-TEST/Codecoverage_in_Netbeans.html)

**Comment by MalteMagnussen** [comment]
>Requires that [#117](https://tree.taiga.io/project/maltemagnussen-fog/task/117?kanban-status=1592820) is done.

It is now done.

**Comment by MalteMagnussen** [comment]
> We should consider the discussed idea of reversing header & footer functions for .JSP pages.
Issue: footer.jsp and header.jsp currently have imports that are unnecessary on various other .jsp-pages.

Starting work on this issue.
Will make header and footer into a master.jsp that then includes whatever other .jsp we need. 
Or at least attempt to.

**Comment by MalteMagnussen** [comment]
>We should consider the discussed idea of reversing header & footer functions for .JSP pages.
Issue: footer.jsp and header.jsp currently have imports that are unnecessary on various other .jsp-pages.

#67 - Proposed solution.

**Comment by Runi-VN** [comment]
>CSS/Javascript consolidation  
suggested: pull https://github.com/HrBjarup/Fog-Carport/pull/77
