### ISSUE TITLE
Mappers need refactoring

### ISSUE THREAD

**Issue by Castau** [HrBjarup/Fog-Carport#46]
Mappers should not close the connection to the database as long as the connection is a singleton at least, it makes the program take forever to test and run, as the database is called a lot in the logic.

**Comment by MalteMagnussen** [comment]
Pretty important we get this done as soon as possible. I feel your pain now Camilla. Can you do this when you have time next? :) @Castau

**Comment by MalteMagnussen** [comment]
Fixed in #54
