### ISSUE TITLE
Shed Drowdown items are unordered.

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#72]
![image](https://user-images.githubusercontent.com/11192971/57393807-2e8c8300-71c4-11e9-8e75-388aa1b07814.png)

**Comment by HrBjarup** [comment]
This bug used to exist when the JavaScript wasn't done yet, but i fixed it and checked it before i pushed the branch and requested merge with developer. I don't understand why the bug is back but I will work on a fix now

**Comment by HrBjarup** [comment]
![image](https://user-images.githubusercontent.com/44898491/57403860-ea58ad00-71da-11e9-91d8-121b91a498a7.png)
I can't find the bug in the Shed Menu (I have pulled latest changes from Developer branch)

**Comment by MalteMagnussen** [comment]
Okay, I might've been on an older version then.

**Comment by HrBjarup** [comment]
![image](https://user-images.githubusercontent.com/44898491/57446221-81ae1680-7254-11e9-9326-ff11c125ddc6.png)
Apparently I how the problem now even though I couldn't find the problem yesterday..

**Comment by HrBjarup** [comment]
I think I know why i happens. Will work on it later today

**Comment by Runi-VN** [comment]
@HrBjarup made a fix here: https://github.com/HrBjarup/Fog-Carport/pull/80
