### ISSUE TITLE
Links from Home page are still bugged

### ISSUE THREAD

**Issue by HrBjarup** [HrBjarup/Fog-Carport#74]
![image](https://user-images.githubusercontent.com/44898491/57403659-78806380-71da-11e9-9a7a-b1a216f3b1b8.png)

**Comment by HrBjarup** [comment]
![image](https://user-images.githubusercontent.com/44898491/57403701-8b933380-71da-11e9-8c0b-6b6c4b7e4085.png)

**Comment by MalteMagnussen** [comment]
#76 - Pull Request containing fix.
