### ISSUE TITLE
Navbar JS bug after link-change

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#78]
Navbar .active JS doesn't work after the link-change:
![image](https://user-images.githubusercontent.com/37186286/57415891-1fc2c200-71fe-11e9-9d38-b32a94d03641.png)

**Comment by MalteMagnussen** [comment]
Probably unable to solve this as a bug.

We have to find an entirely new solution most likely.

The approach I used originally is no longer viable after all our refactoring.

Also, it is just a small thing, so its not that important. To make it look nice, we should probably just delete the navbar JS and then add the active class to every li element.
