### ISSUE TITLE
Fix index.jsp to be handled by FrontController

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#79]
This is what was suggested by AKA

![image](https://user-images.githubusercontent.com/37186286/57444700-04cd6d80-7251-11e9-9889-e79e22ff4f6a.png)

**Comment by MalteMagnussen** [comment]
Starting work on this now in new branch.

**Comment by MalteMagnussen** [comment]
Proposed fix in #81
