### ISSUE TITLE
Improve index.jsp

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#8]
Make index.jsp prettier and more inviting. 
Maybe make some pretty design or something. At least delete the testcode made on day one before friday.
![image](https://user-images.githubusercontent.com/11192971/56657590-b76dcf80-6698-11e9-905f-2a2c2fe69e43.png)

**Comment by Runi-VN** [comment]
suggested changes: https://github.com/HrBjarup/Fog-Carport/pull/21

**Comment by MalteMagnussen** [comment]
Very nice job @Runi-VN
