### ISSUE TITLE
UnknownCommand-message incorrectly displayed on frontpage

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#82]
After the fix for issue https://github.com/HrBjarup/Fog-Carport/issues/79 this happens once you load the frontpage:

![image](https://user-images.githubusercontent.com/37186286/57456044-deb5c680-726c-11e9-9fd2-41d2d908a5df.png)

**Comment by MalteMagnussen** [comment]
I have fixed this in an upcoming version.

**Comment by MalteMagnussen** [comment]
Just tested again on Developer and the fix is now live on Developer.

**Comment by MalteMagnussen** [comment]
Closing issue.
