### ISSUE TITLE
Make table header for the Partslist.jsp sticky to the top

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#88]
https://getbootstrap.com/docs/4.3/utilities/position/
Sticky top
Position an element at the top of the viewport, from edge to edge, but only after you scroll past it. The .sticky-top utility uses CSS’s position: sticky, which isn’t fully supported in all browsers.

IE11 and IE10 will render position: sticky as position: relative. As such, we wrap the styles in a @supports query, limiting the stickiness to only browsers that can render it properly.

Copy
`<div class="sticky-top">...</div>`

**Comment by Castau** [comment]
Will be fixed in this task [https://tree.taiga.io/project/maltemagnussen-fog/task/158?kanban-status=1592820](url)
