### ISSUE TITLE
Order Creation: customer info is not properly set

### ISSUE THREAD

**Issue by Runi-VN** [HrBjarup/Fog-Carport#93]
During PO meeting 10/05 there was an error on "build_address must not be null"

**Comment by MalteMagnussen** [comment]
https://tree.taiga.io/project/maltemagnussen-fog/task/171?kanban-status=1592820

**Comment by MalteMagnussen** [comment]
[Fixed here. ](https://github.com/HrBjarup/Fog-Carport/commit/84d27fbf4913716dc4af50ec473087f30e2622be#diff-b001d59ce6b76a898e2fd280a8459609)

**Comment by MalteMagnussen** [comment]
There were some issues left. [Fixed here.](https://github.com/HrBjarup/Fog-Carport/commit/20f70d8b4df6815f39eb34fad70a28b7939de8e0)
