### ISSUE TITLE
Change the image in login css to a cool example of our own drawings.

### ISSUE THREAD

**Issue by MalteMagnussen** [HrBjarup/Fog-Carport#99]
[Fix it when this is done.](https://tree.taiga.io/project/maltemagnussen-fog/task/148?kanban-status=1592820)

It has to be 600x1200.

Change it inside the global.css
![image](https://user-images.githubusercontent.com/11192971/57541758-0af64380-7350-11e9-982c-6363afadf7d5.png)

![image](https://user-images.githubusercontent.com/11192971/57541692-ec904800-734f-11e9-9887-d5e18b56dc06.png)

**Comment by Castau** [comment]
This issue will be fixed in [task#162](https://github.com/HrBjarup/Fog-Carport/pull/128)

**Comment by MalteMagnussen** [comment]
Has not been fixed on dev yet

**Comment by Castau** [comment]
https://github.com/HrBjarup/Fog-Carport/pull/169
